package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/_GradeServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public class _GradeServiceStub extends org.omg.CORBA.portable.ObjectImpl implements cn.sdu.edu.middleware.excise2_2.daos.beans.GradeService
{

  public cn.sdu.edu.middleware.excise2_2.daos.beans.Grade[] list ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("list", true);
                $in = _invoke ($out);
                cn.sdu.edu.middleware.excise2_2.daos.beans.Grade $result[] = cn.sdu.edu.middleware.excise2_2.daos.beans.GradesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return list (        );
            } finally {
                _releaseReply ($in);
            }
  } // list


  // 0Ð*f@	Ñîé
  public cn.sdu.edu.middleware.excise2_2.daos.beans.Grade[] getGrades (int examNo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGrades", true);
                $out.write_long (examNo);
                $in = _invoke ($out);
                cn.sdu.edu.middleware.excise2_2.daos.beans.Grade $result[] = cn.sdu.edu.middleware.excise2_2.daos.beans.GradesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGrades (examNo        );
            } finally {
                _releaseReply ($in);
            }
  } // getGrades


  // 0Ð*fÐèþé
  public int getGrade (int examNo, int subjectNo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGrade", true);
                $out.write_long (examNo);
                $out.write_long (subjectNo);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGrade (examNo, subjectNo        );
            } finally {
                _releaseReply ($in);
            }
  } // getGrade


  // 0Ð*f@	Ñîé
  public void setGrade (int examNo, int subjectNo, int score)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setGrade", true);
                $out.write_long (examNo);
                $out.write_long (subjectNo);
                $out.write_long (score);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setGrade (examNo, subjectNo, score        );
            } finally {
                _releaseReply ($in);
            }
  } // setGrade

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Beans/GradeService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GradeServiceStub
