package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/_SubjectServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public class _SubjectServiceStub extends org.omg.CORBA.portable.ObjectImpl implements cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectService
{

  public void save (cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("save", true);
                cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectHelper.write ($out, subject);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                save (subject        );
            } finally {
                _releaseReply ($in);
            }
  } // save

  public void delete (int subjectNo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delete", true);
                $out.write_long (subjectNo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delete (subjectNo        );
            } finally {
                _releaseReply ($in);
            }
  } // delete

  public void update (cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("update", true);
                cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectHelper.write ($out, subject);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                update (subject        );
            } finally {
                _releaseReply ($in);
            }
  } // update

  public cn.sdu.edu.middleware.excise2_2.daos.beans.User find (int subjectNo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("find", true);
                $out.write_long (subjectNo);
                $in = _invoke ($out);
                cn.sdu.edu.middleware.excise2_2.daos.beans.User $result = cn.sdu.edu.middleware.excise2_2.daos.beans.UserHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return find (subjectNo        );
            } finally {
                _releaseReply ($in);
            }
  } // find

  public cn.sdu.edu.middleware.excise2_2.daos.beans.Subject[] list ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("list", true);
                $in = _invoke ($out);
                cn.sdu.edu.middleware.excise2_2.daos.beans.Subject $result[] = cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return list (        );
            } finally {
                _releaseReply ($in);
            }
  } // list

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Beans/SubjectService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _SubjectServiceStub
