package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/GradeServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public interface GradeServiceOperations 
{
  cn.sdu.edu.middleware.excise2_2.daos.beans.Grade[] list ();

  // 0Ð*f@	Ñîé
  cn.sdu.edu.middleware.excise2_2.daos.beans.Grade[] getGrades (int examNo);

  // 0Ð*fÐèþé
  int getGrade (int examNo, int subjectNo);

  // 0Ð*f@	Ñîé
  void setGrade (int examNo, int subjectNo, int score);
} // interface GradeServiceOperations
