package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/Grade.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public final class Grade implements org.omg.CORBA.portable.IDLEntity
{
  public cn.sdu.edu.middleware.excise2_2.daos.beans.User user = null;
  public cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject = null;
  public int score = (int)0;
  public String subjectName;
  public int examNo;

  public Grade ()
  {
  } // ctor

  public Grade (cn.sdu.edu.middleware.excise2_2.daos.beans.User _user, cn.sdu.edu.middleware.excise2_2.daos.beans.Subject _subject, int _score)
  {
    user = _user;
    subject = _subject;
    score = _score;
  } // ctor

} // class Grade
