package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/GradeServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public abstract class GradeServicePOA extends org.omg.PortableServer.Servant
 implements cn.sdu.edu.middleware.excise2_2.daos.beans.GradeServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("list", new java.lang.Integer (0));
    _methods.put ("getGrades", new java.lang.Integer (1));
    _methods.put ("getGrade", new java.lang.Integer (2));
    _methods.put ("setGrade", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Beans/GradeService/list
       {
         cn.sdu.edu.middleware.excise2_2.daos.beans.Grade $result[] = null;
         $result = this.list ();
         out = $rh.createReply();
         cn.sdu.edu.middleware.excise2_2.daos.beans.GradesHelper.write (out, $result);
         break;
       }


  // 0Ð*f@	Ñîé
       case 1:  // Beans/GradeService/getGrades
       {
         int examNo = in.read_long ();
         cn.sdu.edu.middleware.excise2_2.daos.beans.Grade $result[] = null;
         $result = this.getGrades (examNo);
         out = $rh.createReply();
         cn.sdu.edu.middleware.excise2_2.daos.beans.GradesHelper.write (out, $result);
         break;
       }


  // 0Ð*fÐèþé
       case 2:  // Beans/GradeService/getGrade
       {
         int examNo = in.read_long ();
         int subjectNo = in.read_long ();
         int $result = (int)0;
         $result = this.getGrade (examNo, subjectNo);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  // 0Ð*f@	Ñîé
       case 3:  // Beans/GradeService/setGrade
       {
         int examNo = in.read_long ();
         int subjectNo = in.read_long ();
         int score = in.read_long ();
         this.setGrade (examNo, subjectNo, score);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Beans/GradeService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GradeService _this() 
  {
    return GradeServiceHelper.narrow(
    super._this_object());
  }

  public GradeService _this(org.omg.CORBA.ORB orb) 
  {
    return GradeServiceHelper.narrow(
    super._this_object(orb));
  }


} // class GradeServicePOA
