package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/SubjectServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public interface SubjectServiceOperations 
{
  void save (cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject);
  void delete (int subjectNo);
  void update (cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject);
  cn.sdu.edu.middleware.excise2_2.daos.beans.User find (int subjectNo);
  cn.sdu.edu.middleware.excise2_2.daos.beans.Subject[] list ();
} // interface SubjectServiceOperations
