package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/Subject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public final class Subject implements org.omg.CORBA.portable.IDLEntity
{
  public int subjectNo = (int)0;
  public String subjectName = null;

  public Subject ()
  {
  } // ctor

  public Subject (int _subjectNo, String _subjectName)
  {
    subjectNo = _subjectNo;
    subjectName = _subjectName;
  } // ctor

} // class Subject
