package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/SubjectServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public abstract class SubjectServicePOA extends org.omg.PortableServer.Servant
 implements cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("save", new java.lang.Integer (0));
    _methods.put ("delete", new java.lang.Integer (1));
    _methods.put ("update", new java.lang.Integer (2));
    _methods.put ("find", new java.lang.Integer (3));
    _methods.put ("list", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Beans/SubjectService/save
       {
         cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject = cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectHelper.read (in);
         this.save (subject);
         out = $rh.createReply();
         break;
       }

       case 1:  // Beans/SubjectService/delete
       {
         int subjectNo = in.read_long ();
         this.delete (subjectNo);
         out = $rh.createReply();
         break;
       }

       case 2:  // Beans/SubjectService/update
       {
         cn.sdu.edu.middleware.excise2_2.daos.beans.Subject subject = cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectHelper.read (in);
         this.update (subject);
         out = $rh.createReply();
         break;
       }

       case 3:  // Beans/SubjectService/find
       {
         int subjectNo = in.read_long ();
         cn.sdu.edu.middleware.excise2_2.daos.beans.User $result = null;
         $result = this.find (subjectNo);
         out = $rh.createReply();
         cn.sdu.edu.middleware.excise2_2.daos.beans.UserHelper.write (out, $result);
         break;
       }

       case 4:  // Beans/SubjectService/list
       {
         cn.sdu.edu.middleware.excise2_2.daos.beans.Subject $result[] = null;
         $result = this.list ();
         out = $rh.createReply();
         cn.sdu.edu.middleware.excise2_2.daos.beans.SubjectsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Beans/SubjectService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SubjectService _this() 
  {
    return SubjectServiceHelper.narrow(
    super._this_object());
  }

  public SubjectService _this(org.omg.CORBA.ORB orb) 
  {
    return SubjectServiceHelper.narrow(
    super._this_object(orb));
  }


} // class SubjectServicePOA
