package cn.sdu.edu.middleware.excise2_2.daos.beans;


/**
* Beans/UserServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_2/daos/dao.idl
* Thursday, November 28, 2013 1:28:44 PM CST
*/

public class UserServicePOATie extends UserServicePOA
{

  // Constructors

  public UserServicePOATie ( cn.sdu.edu.middleware.excise2_2.daos.beans.UserServiceOperations delegate ) {
      this._impl = delegate;
  }
  public UserServicePOATie ( cn.sdu.edu.middleware.excise2_2.daos.beans.UserServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public cn.sdu.edu.middleware.excise2_2.daos.beans.UserServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (cn.sdu.edu.middleware.excise2_2.daos.beans.UserServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void save (cn.sdu.edu.middleware.excise2_2.daos.beans.User user)
  {
    _impl.save(user);
  } // save

  public void delete (int examNo)
  {
    _impl.delete(examNo);
  } // delete

  public void update (cn.sdu.edu.middleware.excise2_2.daos.beans.User user)
  {
    _impl.update(user);
  } // update

  public cn.sdu.edu.middleware.excise2_2.daos.beans.User find (int examNo)
  {
    return _impl.find(examNo);
  } // find

  public cn.sdu.edu.middleware.excise2_2.daos.beans.User[] list ()
  {
    return _impl.list();
  } // list

  private cn.sdu.edu.middleware.excise2_2.daos.beans.UserServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class UserServicePOATie
