package cn.sdu.edu.middleware.excise2_1.MyServer;


/**
* MyServer/MyServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_1/simple.idl
* Wednesday, November 27, 2013 9:47:26 PM CST
*/

public class MyServicePOATie extends MyServicePOA
{

  // Constructors

  public MyServicePOATie ( cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public MyServicePOATie ( cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void operation1 (String msg)
  {
    _impl.operation1(msg);
  } // operation1

  private cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MyServicePOATie
