package cn.sdu.edu.middleware.excise2_1.MyServer;


/**
* MyServer/MyService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_1/simple.idl
* Wednesday, November 27, 2013 9:47:26 PM CST
*/

public interface MyService extends MyServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MyService
