package cn.sdu.edu.middleware.excise2_1.MyServer;

/**
* MyServer/MyServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_1/simple.idl
* Wednesday, November 27, 2013 9:47:26 PM CST
*/

public final class MyServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public cn.sdu.edu.middleware.excise2_1.MyServer.MyService value = null;

  public MyServiceHolder ()
  {
  }

  public MyServiceHolder (cn.sdu.edu.middleware.excise2_1.MyServer.MyService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceHelper.type ();
  }

}
