package cn.sdu.edu.middleware.excise2_1.MyServer;


/**
* MyServer/MyServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from H:/repositoy/corbaPractice/src/main/java/cn/sdu/edu/middleware/excise2_1/simple.idl
* Wednesday, November 27, 2013 9:47:26 PM CST
*/

public abstract class MyServicePOA extends org.omg.PortableServer.Servant
 implements cn.sdu.edu.middleware.excise2_1.MyServer.MyServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("operation1", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MyServer/MyService/operation1
       {
         String msg = in.read_string ();
         this.operation1 (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MyServer/MyService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MyService _this() 
  {
    return MyServiceHelper.narrow(
    super._this_object());
  }

  public MyService _this(org.omg.CORBA.ORB orb) 
  {
    return MyServiceHelper.narrow(
    super._this_object(orb));
  }


} // class MyServicePOA
